services:
  app:
    image: maven:3.9.8-eclipse-temurin-21
    container_name: spring_app_dev
    working_dir: /app
    command: mvn spring-boot:run
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PWD=${EMAIL_PWD}
    volumes:
      - ./LoginCliente:/app
    ports:
      - "${APP_RETURN_PORT}:8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_DB=Contabilidad
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "${DB_RETURN_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
